# Generated by Django 5.0.1 on 2024-01-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='types',
            new_name='type',
        ),
    ]
