# Generated by Django 5.0.1 on 2024-01-16 02:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(db_index=True, verbose_name='Price')),
                ('rent_price', models.IntegerField(db_index=True, verbose_name='Rent price')),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Main image')),
                ('sub_image1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Sub image 1')),
                ('sub_image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Sub image 2')),
                ('sub_image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Sub image 3')),
                ('sub_image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Sub image 4')),
                ('state', models.CharField(db_index=True, default='State', max_length=50, verbose_name='State')),
                ('address', models.CharField(db_index=True, default='Address', max_length=50, verbose_name='Address')),
                ('layout', models.CharField(db_index=True, default='2,231 sqft', max_length=50, verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'db_table': 'home',
            },
        ),
    ]
