# Generated by Django 5.0.1 on 2024-01-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellrequest',
            table='sell_request',
        ),
    ]
