# Generated by Django 5.0.1 on 2024-01-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
        ('home', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favourite',
        ),
    ]
